### ISSUE TITLE
请问列表弹出的方向怎么控制？

### ISSUE THREAD

**Issue by xiaobeifeng** [pandas16/react-native-selfadapt-modal#2]

**Comment by pandas16** [comment]
现在是根据弹框展开的位置来判断的，在屏幕中位线以上则向下展开，在屏幕中位线以下则向上展开

**Comment by pandas16** [comment]
> _No description provided._



> _No description provided._
现在是根据弹框展开的位置来判断的，在屏幕中位线以上则向下展开，在屏幕中位线以下则向上展开
