### ISSUE TITLE
获取不到SelfadaptModal 的展开与收起

### ISSUE THREAD

**Issue by a728384698** [pandas16/react-native-selfadapt-modal#5]
获取不到SelfadaptModal 的展开与收起 没办法控制箭头方向，请问是有什么其他方式吗

**Comment by pandas16** [comment]
> 获取不到SelfadaptModal的展开与收起没办法控制箭头方向，请问是有什么其他方吗

已修复，可以使用回调函数openStatus实现，详情可查阅Demo，更新不及时请谅解
